// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdLZwixynu1OrsVlM-CZeOC7OEvhLhP1k',
    appId: '1:606003359472:web:30957e7a21f4a2005c9c35',
    messagingSenderId: '606003359472',
    projectId: 'simpleconnect-a3b70',
    authDomain: 'simpleconnect-a3b70.firebaseapp.com',
    storageBucket: 'simpleconnect-a3b70.firebasestorage.app',
    measurementId: 'G-5VX9MJ3KXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD0ELiWbCXnyMkEpHIiUeynBvJKOapxa4',
    appId: '1:606003359472:android:fab20b501d67a10d5c9c35',
    messagingSenderId: '606003359472',
    projectId: 'simpleconnect-a3b70',
    storageBucket: 'simpleconnect-a3b70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnhovVOWq3xsW3JvAUCjA6fcaZxHmPjQE',
    appId: '1:606003359472:ios:b13a7bc3829b2d8e5c9c35',
    messagingSenderId: '606003359472',
    projectId: 'simpleconnect-a3b70',
    storageBucket: 'simpleconnect-a3b70.firebasestorage.app',
    iosBundleId: 'com.siva.sampleconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnhovVOWq3xsW3JvAUCjA6fcaZxHmPjQE',
    appId: '1:606003359472:ios:b13a7bc3829b2d8e5c9c35',
    messagingSenderId: '606003359472',
    projectId: 'simpleconnect-a3b70',
    storageBucket: 'simpleconnect-a3b70.firebasestorage.app',
    iosBundleId: 'com.siva.sampleconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdLZwixynu1OrsVlM-CZeOC7OEvhLhP1k',
    appId: '1:606003359472:web:7bac9b830887e3f35c9c35',
    messagingSenderId: '606003359472',
    projectId: 'simpleconnect-a3b70',
    authDomain: 'simpleconnect-a3b70.firebaseapp.com',
    storageBucket: 'simpleconnect-a3b70.firebasestorage.app',
    measurementId: 'G-VB2WEMXCGK',
  );
}
