name: Sample Connect CI/CD

on:
  push:
    branches:
      - "sample"
env:
  JAVA_VERSION: "17"
  FLUTTER_VERSION: "3.27.3"

jobs:
  build:
    name: Build Flutter App and Distribute to Firebase
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}  # replace with your Flutter version
      - name: Set up Firebase credentials
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > firebase_credentials.json

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload release to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: sampleTest
          file: build/app/outputs/flutter-apk/app-release.apk
#          serviceCredentialsFile: firebase_credentials.json
